In [1]:
import numpy as np

In [51]:
mylist = [1,2,3,4]
np.array(mylist)

array([1, 2, 3, 4])

In [50]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(0, 100, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [48]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [46]:
np.random.randint(0,100)

56

In [45]:
np.random.randint(0,100,(5,5))

array([[49, 83,  8, 29, 59],
       [34, 44, 72, 19, 10],
       [76, 95, 87,  0, 73],
       [ 8, 62, 36, 83, 99],
       [28, 63,  7, 10, 52]])

In [44]:
np.linspace(0,100,38)

array([  0.        ,   2.7027027 ,   5.40540541,   8.10810811,
        10.81081081,  13.51351351,  16.21621622,  18.91891892,
        21.62162162,  24.32432432,  27.02702703,  29.72972973,
        32.43243243,  35.13513514,  37.83783784,  40.54054054,
        43.24324324,  45.94594595,  48.64864865,  51.35135135,
        54.05405405,  56.75675676,  59.45945946,  62.16216216,
        64.86486486,  67.56756757,  70.27027027,  72.97297297,
        75.67567568,  78.37837838,  81.08108108,  83.78378378,
        86.48648649,  89.18918919,  91.89189189,  94.59459459,
        97.2972973 , 100.        ])

In [52]:
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [43]:
a = np.random.randint(0,100,10)
print(a)

[ 4 63 40 60 92 64  5 12 93 40]


In [41]:
a.max()

93

In [40]:
a.min()

4

In [39]:
a.mean()

47.3

In [38]:
a.reshape(2,5)

array([[ 4, 63, 40, 60, 92],
       [64,  5, 12, 93, 40]])

In [23]:
f = np.arange(0,100).reshape(10,10)
print(f)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [37]:
f[3][5]

35

In [36]:
f[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [35]:
f[3,:3]

array([30, 31, 32])

In [34]:
f[3,3:6]

array([33, 34, 35])

In [32]:
f[3,-3]

37

In [33]:
f > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [31]:
f[f>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])